### ISSUE TITLE
v0.0.9 error spam (game unresponsive)

### ISSUE THREAD

**Issue by awdwyn** [sbtoonz/BackPacks_Remake#18]
Not sure what's causing this, but after upgrading from 0.0.6 to 0.0.9 I'm getting the following error spam in my bepinex log:

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BackPacks.Patches+GetTotalWeightPatch.Postfix (Inventory __instance, System.Single& __result) (at <b92a7b1f10154d15adc46a6b9d955ef9>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::GetTotalWeight>(Inventory)
Player.IsEncumbered () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
Character.UpdateWalking (System.Single dt) (at <0b427da81d26480c885ae3fba0ed94c4>:0)
Character.UpdateMotion (System.Single dt) (at <0b427da81d26480c885ae3fba0ed94c4>:0)
(wrapper dynamic-method) Character.DMD<Character::FixedUpdate>(Character)
Humanoid.FixedUpdate () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
(wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BackPacks.Patches+GetTotalWeightPatch.Postfix (Inventory __instance, System.Single& __result) (at <b92a7b1f10154d15adc46a6b9d955ef9>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::GetTotalWeight>(Inventory)
Player.IsEncumbered () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
(wrapper dynamic-method) Player.DMD<Player::CanMove>(Player)
(wrapper dynamic-method) CharacterAnimEvent.DMD<CharacterAnimEvent::FixedUpdate>(CharacterAnimEvent)`

It continues until I force quit the game. I rolled back to 0.0.6 and deleted the backpack I had, then upgraded (which worked fine), nit the error spam started up again as soon as I crafted a new fine backpack.

**Comment by sbtoonz** [comment]
Please upload a log output from an effected game session
