### ISSUE TITLE
crash on latest version

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#19]
My mod profile code: SRgSaqqenY 
My crash logs: [Player.log](https://github.com/sbtoonz/BackPacks_Remake/files/8088214/Player.log)
How to reproduce: I added about 50 iron bars in my backpack (with 15% move speed reduce, and 50% weight in backpack reduce)
I was walking on stone (Speedy mod changes speed values too)

Mod list I use atm (35 mods):
```
denikson-BepInExPack_Valheim-5.4.1900
RandyKnapp-EquipmentAndQuickSlots-2.0.14
abearcodes-CraftingWithContainers-1.0.14
RandyKnapp-ExtendedItemDataFramework-1.0.7
RandyKnapp-EpicLoot-0.8.8
MaGic-Quick_Deposit-1.0.1
ValheimPlus-ValheimPlus-9.9.7
LVH-IT-FasterTeleportation-0.3.1
ToastyWzrd-HoldAttack-0.4.2
LVH-IT-UseEquipmentInWater-0.2.2
Smoothbrain-CreatureLevelAndLootControl-4.4.5
virtuaCode-TrashItems-1.2.4
nearbear-CustomSlotItemLib-1.0.4
nearbear-WishboneSlot-1.0.3
Nexus-InstantMonsterLootDrop-0.2.11
tonsit-InteractWhileBuilding-1.0.0
Nextek-SpeedyPaths-1.0.5
Crystal-Pathfinder-2.0.5
RandyKnapp-ImprovedBuildHud-1.0.2
virtuaCode-EmoteWheel-1.3.1
clevel-BeastsOfBurden-1.0.4
OdinPlus-OdinHorse-0.2.0
OdinPlus-Better_Trader_Remake-2.1.1
thedefside-BetterUI_Reforged-2.1.0
OdinPlus-StackedBars-1.0.0
ValheimModding-HookGenPatcher-0.0.3
ValheimModding-Jotunn-2.5.1
Smallo-CraftingStationsLevelBasedBuildRange-1.5.0
OdinPlus-BackPacks_Remake-0.0.9
OdinPlus-ChickenBoo-2.1.3
cjayride-DropSingleItem-1.1.0
MSchmoecker-MultiUserChest-0.1.0
MaxiMods-MultiCraft-1.0.0
OdinPlus-Digitalroots_EpicLoot_Adventure_Bounties-2.1.2
cjayride-ConfigurationManager-0.5.0
```

**Comment by lupuleasa-core** [comment]
unsure if it is related to this mod, but it is likely as I just erased the backpack config and downloaded the new version, and this is the only mod that is new. it happened after running for 5 seconds.

**Comment by lupuleasa-core** [comment]
Tried again to reproduce it on a fresh world, it doesn't seem to occur no longer. 

Extra information: I had a backpack crafted from a prev version.

**Comment by sbtoonz** [comment]
Thank you for leaving steps to reproduce 
I will attempt to reproduce bug and isolate fix

**Comment by lupuleasa-core** [comment]
I couldn't reproduce this one either after playing 30 minutes more

After I restored the backup to my world

Maybe the issue is when upgrading from 0.6 to 0.9, if you had a backpack crafted from prev versions

**Comment by lupuleasa-core** [comment]
Excellent

Now I can finally release the pack (a Vanilla Valheim Expanded pack), the backpack was the only thing that was too cool not to add, but I waited for stability fixes
