### ISSUE TITLE
Suggestion: Add UI button to "Open Backpack" on inventory menu

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#2]
Right now, new players on my server will never know the backpack has storage.

**Comment by sbtoonz** [comment]
Starting this next

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/154345684-28deb6d9-3786-4c21-aad2-71a9cca9473b.png)

**Comment by lupuleasa-core** [comment]
really cool
