### ISSUE TITLE
Bug: Items in backpack get deleted

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#22]
I placed 60 iron bars in bag
Unequipped it (from Inventory mod)
Bag weights 426 
Thrown it on ground
Pick up
Equip bag
Back weighs 4 and is empty

Profile code: SRgSaqqenY

**Comment by lupuleasa-core** [comment]
Tested it some more: You don't even have to throw it on ground

You just need to equip it inside the Equipment mod and it "forgets" items
![image](https://user-images.githubusercontent.com/5671120/154475758-bcef9ce2-bef8-4e36-a570-0fdaf4fe7bcc.png)

So I guess that means it is incompatible with EquipmentAndQuickSlots atm

**Comment by lupuleasa-core** [comment]
Dropping on ground and picking up works fine
![image](https://user-images.githubusercontent.com/5671120/154476208-ed082ca6-f0ff-4668-a7a0-d364ee26ba4d.png)

It is only when equipping the bag that items get deleted

**Comment by sbtoonz** [comment]
This is extended item quick slots by randy Knapp as well?

**Comment by lupuleasa-core** [comment]
Quick slots are disabled in my setup, only inventory slots remain

**Comment by sbtoonz** [comment]
> Quick slots are disabled in my setup, only inventory slots remain

should be resolved in new thunderstore upload
