### ISSUE TITLE
0.1.2 -> 0.1.3: Singular weapons equipped in dual wield

### ISSUE THREAD

**Issue by annex4** [sbtoonz/BackPacks_Remake#26]
When equipping a one handed mace or axe (didn't test sword) and you have DualWield installed the singular weapon will be equipped in dual wield fashion. A secondary weapon from seemingly nowhere will be equipped in the offhand.

This issue does not exist in v0.1.2

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/download/untagged-2c2a0d9919a55099aa62/BackPacks.dll

please try this and report back

**Comment by sbtoonz** [comment]
Validated with DualWield by smoothbrain on thunderstore this version is working posted as release verion to tstore
