### ISSUE TITLE
Backpacks wont open until unequiped/reequiped

### ISSUE THREAD

**Issue by RapidHabit** [sbtoonz/BackPacks_Remake#32]
Sbtoonz,
For starters, Thanks for creating a very cool mod!   My group and I have spoken about the idea of Valheim adding some form of backpack feature and we love the mod concept you've created!  With that said we've been having the following issues since installation yesterday (version 2.2) 

*  Backpack often does not open upon pressing Shift+E. 
Context:  The bags in question were leather backpacks upgraded to level 2.  The fix in all cases seemed to be to unequip the backpack and reequip (though this isn't ideal given how many times this happened over the course of a 2 hour play session). 

*  Upon dying the backpack was able to be looted off a 'grave' but showed the players inventory weight as being the total weight of the contents of the bag, not just the 4lbs the bag weighed even after initially equipping the bag.
Context:  Bag is set to decrease the weight of all items stored within it by 40% and slows movement speed by 5%.  It should be noted that unequipping and reequipping the bag a second time did appear to fix the issue in this specific case as well.  

Current Mods on the server (as it may - and likely is - due to some sort of mod conflict):
Valheim Plus
Any Portal
Plant Everything
Clutter
MoreUpgrades
Bears
BoneAppetit
Dual Wield
Whistlr
and the required mod extensions to support some of the above mods:
Jotunn the Valheim Library
Extended Item Data Framework

Anything you can do to correct this bug would be GREATLY appreciated.  We will continue to run the mod even with this issue as we really enjoy the concept, but im hopeful youll be able to find a fix for this.

**Comment by sbtoonz** [comment]
The bag will assume the weight of its contents multiplied by the decimal you have in the config for alter weight contents 
so if you have set to .4 
It would be something to the extend of InventoryWeight * 0.4 = X

and then assign the bag itself the weight of X 

The weight adjustment will only occur during bag wear time and then on unequip based on config value.

So if you put 10 pieces of wood in your bag (that totals 200)
and your bag is set to 0.4 
200 * 0.4 = 80 
so bag would weigh 84 


Are you able to test a version that should resolve the upgrade issue? I can post it in the releases portion of this git

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/V0.2.3-Testing

**Comment by RapidHabit** [comment]
Wow!  Did not expect such a quick response.  Awesome! :)

I think I found the problem with regards to the non opening bag.  It seems the E key is leveraged by valheim so shift E was confusing the console I believe.  Upon switching the hot key to B (this shift+B) I have not experienced the issue.  I plan to try this with the group this evening to see if it corrects the non-opening issue and will let you know.

In regards to the weight, I meant I adjusted it so contents within the bag weigh 40% less, not the bag itself. It appeared upon picking up all items from the grave that my inventory went well over the amount I was carrying because it was seeing all items in the bag as full weight even upon first equipping the bag. As stated before upon unequipping and reequipping it, the weight corrected to the proper amount.

**Comment by RapidHabit** [comment]
I've installed the test version but will not be able to thoroughly test until this evening.  Will report back once we've tried the updated version.

**Comment by sbtoonz** [comment]
Should be resolved in thunderstore version

**Comment by RapidHabit** [comment]
tested version 2.4 last night.  backpacks are still a little buggy but worked without the need to re-equip.  we found that in multiplayer instances if another player is performing an action nearby while a player is opening their backpack the backpack will bug and not open during the period the other player is performing their action.  If the other player stops their current action however, the player attempting to open their bag will be able to open the bag successfully.  Once the bag is open, the other player can begin performing their actions again without impacting the player migrating items to their bag etc.   As an example: at one point last night one player (player A) was attempting to mine iron ore while another (Player B) was attempting to open their bag and move their ore to the backpack.  The backpack would not open for Player B until Player A stopped mining ore and waited.  Once the bag was open however, Player A could begin mining again while Player B moved items around in his inventory.
