### ISSUE TITLE
Had an Issue on logout 

### ISSUE THREAD

**Issue by Ernb4s** [sbtoonz/BackPacks_Remake#35]
got a red text (Error) on Logout... Havent tried the backpack ingame cause another mod already completely crashed a character savefile so a little bit a little bit scared ^^

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetView.IsOwner () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
BackPack.DeRegisterRPC () (at <16f748fafdd94459bf84735460c511fd>:0)
BackPack.OnDisable () (at <16f748fafdd94459bf84735460c511fd>:0)

No Probs till now but guess you should know

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/0.2.4B_test
