### ISSUE TITLE
Suggestion/Bug?: Make the rugged backpack have a cheaper recipe

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#4]
Right now the defaults are that the fine backpack and rugged backpack have same costs.

![image](https://user-images.githubusercontent.com/5671120/154326265-b85c656f-6f53-4859-8130-8589b1960fa8.png)

![image](https://user-images.githubusercontent.com/5671120/154326311-6e97dd88-b9f8-4247-bf8f-d6f06fb33b17.png)

**Comment by sbtoonz** [comment]
Oh Whoops... Looks like I have messed that up  You can always edit crafting values for now but will fixup defaults

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/commit/8a199d4f76cdc6ce9c21db1bdeeb393b8c02d0fb

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/Beta

**Comment by lupuleasa-core** [comment]
super cool speedy boy

any way to test beta release?

I have been learning r2modman past days, but I guess you haven't published the beta for this

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/download/untagged-ddb58bf102909b479154/BackPacks.dll


Take this file and in the R2ModMan settings there is a "manually install mod" option then use this DLL

**Comment by lupuleasa-core** [comment]
cheers

also, quick notice in case you missed it

but the recipe changes should be changed in the configs as well

I will test to see that the configs will regen well
![image](https://user-images.githubusercontent.com/5671120/154350524-220594ed-b974-4d8a-8a7e-bb86b69e22a6.png)

**Comment by lupuleasa-core** [comment]
yes, I need to also delete the configs
