### ISSUE TITLE
UI fails to load sometimes

### ISSUE THREAD

**Issue by Kherae** [sbtoonz/BackPacks_Remake#40]
[errors.txt](https://github.com/sbtoonz/BackPacks_Remake/files/8175523/errors.txt)

managed to get the entire UI to die via the following:
started game, did stuff, logged out. logged in, sprinted past a container (holding shift) and activated container (E).  boom, UI died.

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/download/Testing/BackPacks.dll

**Comment by sbtoonz** [comment]
please try

**Comment by sbtoonz** [comment]
Unable to replicate this issue
