### ISSUE TITLE
0.2.8 all gray in build menu if equiped

### ISSUE THREAD

**Issue by 4Magma** [sbtoonz/BackPacks_Remake#42]
updated to 0.2.8
tried to build something, but all objects gray
over Craft from Containers -> FAIL
with materials in inventory -> FAIL
...
unequiped backpack -> OK
reequiped backpakc -> FAIL

**Comment by 4Magma** [comment]
from aedonthorn but it also FAILS with items in inventory

**Comment by sbtoonz** [comment]
can you temporarily disable craft from container and report if you still suffer this problem
There might be an incompatibility i need to account for

**Comment by 4Magma** [comment]
hammer

**Comment by 4Magma** [comment]
sorry, both hammer and workbench

**Comment by 4Magma** [comment]
sorry again forgot that i removed previous the materials
workbench works with materials in inventory
but hammer fails

**Comment by 4Magma** [comment]
i got a nullreference error when closing valheim, but not at logout

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetView.IsOwner () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
BackPack.OnBackPackChange () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)
Inventory.Changed () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
Inventory.RemoveAll () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
BackPack.DropAllItems () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)
BackPack.OnDisable () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)

**Comment by sbtoonz** [comment]
> i got a nullreference error when closing valheim, but not at logout
> 
> [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: ZNetView.IsOwner () (at :0) BackPack.OnBackPackChange () (at <3b1551cb934846b08a4e359c7fb0bd30>:0) Inventory.Changed () (at :0) Inventory.RemoveAll () (at :0) BackPack.DropAllItems () (at <3b1551cb934846b08a4e359c7fb0bd30>:0) BackPack.OnDisable () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)

this is a separate issue please do not clutter issue threads with multiple problems

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/commit/a296ad4ace1b0ef4ae247e1898fdad0297b84e8f
