### ISSUE TITLE
i got a nullreference error when closing valheim, but not at logout

### ISSUE THREAD

**Issue by sbtoonz** [sbtoonz/BackPacks_Remake#43]
i got a nullreference error when closing valheim, but not at logout

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetView.IsOwner () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
BackPack.OnBackPackChange () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)
Inventory.Changed () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
Inventory.RemoveAll () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
BackPack.DropAllItems () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)
BackPack.OnDisable () (at <3b1551cb934846b08a4e359c7fb0bd30>:0)

_Originally posted by @4Magma in https://github.com/sbtoonz/BackPacks_Remake/issues/42#issuecomment-1060778710_

**Comment by sbtoonz** [comment]
This is only when you close valheim @4Magma? not when you logout

**Comment by 4Magma** [comment]
- saw it when i closed valheim to remove craft from container dll
- started world and logged out -> OK
- started world and exit -> Error

**Comment by sbtoonz** [comment]
OK I will investigate this
