### ISSUE TITLE
Server Synchronization

### ISSUE THREAD

**Issue by Lime18** [sbtoonz/BackPacks_Remake#47]
The following sections in the config do not work (server side):
```
[Carry Bonus]
[Carry Modifiers]
[Move Modifiers]
```
Required settings included
```
Alter Carry Weight = true
Add Carry Bonus = true
Should bags impact movement = true
```
Also doesn't work
`Maximum Crafting Station Level`

P.S `Lock Configuration = true`

**Comment by sbtoonz** [comment]
unable to reproduce
