### ISSUE TITLE
Suggestion/Bug: Silver Backpack is actually made with iron

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#5]
Saw it was noted in the code as "silver" backpack, but crafting cost is iron

Personally I feel backpacks should be tiered by the metals.

Requiring Bronze, Iron, Silver, in that order.

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/commit/8a199d4f76cdc6ce9c21db1bdeeb393b8c02d0fb

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/Beta
