### ISSUE TITLE
Hotkey to open the backpack doesn't work

### ISSUE THREAD

**Issue by Urfin13** [sbtoonz/BackPacks_Remake#50]
Tried rebinding the key in the config and lshift ingame, doesn't work.

No other mods, latest versions of valheim and dependencies.

Would really love to use the mod but the bag won't open :)

**Comment by Urfin13** [comment]
Update: it's actually rebinding that doesn't work for me. It still opens only on LShift+E, no matter what I put in the config.

**Comment by Gianpaul1** [comment]
This also happened to me, but I have a bit more to add:
Background: Dedicated server with 3 players
Issues:
1) Rebinding keys did not work (default bind did work). After several attempts at rebinding and restarting server, rebinding eventually registered and worked correctly. I suspect there may have been some sort of a desync until all 3 players and server had the same bind value and attempted to use it.
2) Hot key will work just fine when only one player is on server. However, when another player comes onto the server, the hotkey will stop working for all players. To fix this, the backpack must be un-equipped and then re-equipped. This will resolve the issue temporarily, but it will return intermitted during the same session forcing an unequip/re-equip process once again to resolve.
3) Not sure if this is related, but the backpack with randomly flag itself as non-transportable (ie. as though it has ore in it). This will also require a equip/unequip procedure)

**Comment by sbtoonz** [comment]
fixed in cac1d34ddf8c4ac72b8de3b6d6a0a4a9863c8181
