### ISSUE TITLE
Jude backpacks are unbalanced

### ISSUE THREAD

**Issue by SipeP** [sbtoonz/BackPacks_Remake#55]
Hello,
First of all - thank you for this mod and all your hard work.

I am using this mod together with Jude's equipment - the Normal backpack has only 2 slots on Lvl1 but the Jude's Simple Backpack has 8 slots on Lvl1 even though it's not much harder to craft.

**Comment by Gianpaul1** [comment]
> 

You can disable Jude's backpacks by opening the config file GoldenJude_JudesEquipment_ItemConfig.yml and scrolling towards the bottom. Under the headings "simple backpack" and "heavy backpack", find where it says "recipe:". Change the value next to "enabled" to "false".

**Comment by SipeP** [comment]
What if I want to use them as well? :(
Seems like Simple Backpack is linked to Iron Bag and Heavy Backpack is linked to Silver bag - cause when I change settings for Iron & Silver bag in com.zarboz.backpacks.cfg it affects Simple & Heavy Backpack as well.
It would be somehow balanced if Simple Backpack was linked with Leather Backpack and Heavy would be linked with Iron Bag.
