### ISSUE TITLE
[Mod Compat] Auga (RandyKnapp) - Double Trash button

### ISSUE THREAD

**Issue by Beauford20** [sbtoonz/BackPacks_Remake#57]
Currently using this list of mods:
BepInExPack_Valheim by denikson
HookGenPatcher by ValheimModding
ValheimPlus by ValheimPlus
ValheimTooler by Astropilot
Auga by RandyKnapp
ExtendedItemDataFramework by RandyKnapp
EquipmentAndQuickSlots by RandyKnapp
CreatureLevelAndLootControl by Smoothbrain
Jotunn by ValheimModding
Terraheim by DasSauerkraut
Blacksmiths_tools by GoldenJude
Judes_Equipment by GoldenJude
---> have both backpacks disabled as I want to use the BackPacks_Remake
BackPacks_Remake by OdinPlus

https://gyazo.com/9db72b73c431215a0d2860804b76890f

Anyone have a work around for the double trash button? I can disable trash in Auga and it will go away but no trash button then.

Thanks for the hard work!

**Comment by sbtoonz** [comment]
trash button from auga itself?

I will see what happened

**Comment by Beauford20** [comment]
Yes, 
UseAugaTrash enable

**Comment by sbtoonz** [comment]
OK I will test with randy's latest version, I had done some light patching to make Auga compatible

**Comment by Beauford20** [comment]
okay sounds good! Thank you for the super quick reply.

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/blob/master/BackPacks/Patches.cs#L284-L302

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/commit/249bffa6244f4c7ead27ae551fd1d8dd6e9d79e6

Whoops totally marked the wrong error

**Comment by Beauford20** [comment]
should be fixed in the next update?

**Comment by sbtoonz** [comment]
> should be fixed in the next update?

yes letting git build a release copy now :D

https://github.com/sbtoonz/BackPacks_Remake/actions/runs/2928613298

**Comment by Beauford20** [comment]
thanks boss! coming in clutch.

**Comment by sbtoonz** [comment]
also odd your thing says "trash" cuz in my test it does its job and replaced the txt with the backpack tooltip

so in my test for 0.4.2 the backpack tooltip no longer is a trash button

**Comment by Beauford20** [comment]
hmm weird, not to sure

**Comment by Beauford20** [comment]
i put the .dll in and still no change for me, I might be doing it wrong though.
