### ISSUE TITLE
Suggestion: Remove blue tarp/cape on Rugged Backpack Model?

### ISSUE THREAD

**Issue by MAA-Alastair** [sbtoonz/BackPacks_Remake#6]
Not sure if its possible, And I don't know if its intentional or not for it to be there, but can the blue tarp/cape be removed from the rugged backpack model? Looks like it clashes and doesn't fit in well.
![image](https://user-images.githubusercontent.com/99830719/154330012-29b61452-3ba8-4e3a-9b79-7dcf791da5d6.png)
![image](https://user-images.githubusercontent.com/99830719/154330055-d55e5e2c-2dee-4d2f-98e2-7201ade715d4.png)
![image](https://user-images.githubusercontent.com/99830719/154330140-2cfeab26-24ad-4d90-a13e-09fecfe5b7c5.png)

**Comment by lupuleasa-core** [comment]
It might also have some clipping issues

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/154340497-114c30ba-4974-4249-984f-86b0c4064182.png)

**Comment by MAA-Alastair** [comment]
Sorry, I also meant to include the part of it that surrounds the neck area. other than that, its perfect. The rugged Backpack model is my favorite looking backpack model by far of the three. And yes, as lup said, the cape and the neck/collar portion part of the model does clip with some vanilla and modded armors. One example is the padded armor when you have the helmet on. The straps for the backpack are perfectly fine however. 
![image](https://user-images.githubusercontent.com/99830719/154400624-dbc0859d-1c31-405b-b601-3581889ac947.png)

**Comment by sbtoonz** [comment]
> Sorry, I also meant to include the part of it that surrounds the neck area. other than that, its perfect. The rugged Backpack model is my favorite looking backpack model by far of the three. And yes, as lup said, the cape and the neck/collar portion part of the model does clip with some vanilla and modded armors. One example is the padded armor when you have the helmet on. The straps for the backpack are perfectly fine however. 
> 
> ![image](https://user-images.githubusercontent.com/99830719/154400624-dbc0859d-1c31-405b-b601-3581889ac947.png)
> 
> 

I actually did this about a hour ago 😂😂

**Comment by MAA-Alastair** [comment]
> 
> I actually did this about a hour ago 😂😂

Ah, alrighty. Well, thank you regardless.

**Comment by sbtoonz** [comment]
> > I actually did this about a hour ago 😂😂
> 
> Ah, alrighty, Because I noticed you removed the part that was on the back, but not the part that looks like its wrapped around the neck area and drapes over the top portion of the back area. Its just to pretty much make it like how the original model made by Cinnabunn is supposed to be.

I think I missed the model on the last upload once I finish testing some stuff ill update the thunderstore version with the proper model

**Comment by lupuleasa-core** [comment]
yeah I noticed it was still there prev patches
